
services:
  web:
    image: dripchip
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:81"
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Database=DripChip;User Id=postgres;Password=313818;
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 313818
      POSTGRES_DB: DripChip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: