@DripChip_HostName = https://localhost:7173

GET {{DripChip_HostName}}/animals/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoibG9naW4iLCJQYXNzd29yZCI6InBhc3N3b3JkIiwiaXNzIjoiRHJpcENoaXBBUEkiLCJhdWQiOiJEcmlwQ2hpcENsaWVudCJ9.mJ2X-FpbEFZm07oTgjEtiNgooZHu_0InzmWeqZG3OkU

###

GET {{DripChip_HostName}}/animals/2
Accept: application/json

###

GET {{DripChip_HostName}}/animals/555
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoibG9naW4iLCJQYXNzd29yZCI6InBhc3N3b3JkIiwiaXNzIjoiRHJpcENoaXBBUEkiLCJhdWQiOiJEcmlwQ2hpcENsaWVudCJ9.mJ2X-FpbEFZm07oTgjEtiNgooZHu_0InzmWeqZG3OkU

###

GET {{DripChip_HostName}}/animals/-55
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoibG9naW4iLCJQYXNzd29yZCI6InBhc3N3b3JkIiwiaXNzIjoiRHJpcENoaXBBUEkiLCJhdWQiOiJEcmlwQ2hpcENsaWVudCJ9.mJ2X-FpbEFZm07oTgjEtiNgooZHu_0InzmWeqZG3OkU

###